### ISSUE TITLE
Execution on buildserver fails

### ISSUE THREAD

**Issue by xp-development** [olsh/dotnet-consolidate#1]
If I install and execute the tool on my local machine, all works fine.

Using the tool on TFS Version 16.131.28601.4 throws an error.

Error message: 
```
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but "dotnet-con
solidate" does not exist.
```

The program name dotnet-consolidate is splitted by a new line. I don't know why.

My script:
```
dotnet tool install dotnet-consolidate --global
dotnet consolidate -s Test.sln
```

**Comment by xp-development** [comment]
I tried another buildserver and the execution works. But no consolidates are found see issue [2](https://github.com/olsh/dotnet-consolidate/issues/2).

**Comment by olsh** [comment]
Should we close the issue?

**Comment by xp-development** [comment]
After restart the buildserver. All works fine.
