### ISSUE TITLE
Package references not found

### ISSUE THREAD

**Issue by xp-development** [olsh/dotnet-consolidate#2]
No package references were found in my csproj files. I debug the code and found two parts that I have to change.

1. To read XML elements it is necessary to add the namespace:
```
var ns = "http://schemas.microsoft.com/developer/msbuild/2003";
var packageReferences = xml.Root.Elements(XName.Get("ItemGroup", ns)).Elements(XName.Get("PackageReference", ns));
```
2. Version is not an attribute. It is an element in my project files.
```
var version = reference.Element(XName.Get("Version", ns));
```

**Comment by olsh** [comment]
Hi @xp-development ,
Thank you for the info 👍 
Could you please provide a demo solution?

**Comment by xp-development** [comment]
[Test.zip](https://github.com/olsh/dotnet-consolidate/files/5486247/Test.zip)

**Comment by olsh** [comment]
Thanks, I'll take a look. 👍

**Comment by olsh** [comment]
The package reference format was added in the 1.1.0 version.

Feel free to reopen the issue if you still have problems with the solution.

**Comment by xp-development** [comment]
The new package works. Thank you!!
