### ISSUE TITLE
Ability to exclude certain packages

### ISSUE THREAD

**Issue by cmeyertons** [olsh/dotnet-consolidate#24]
I see this tool has the ability to _include_ packages, but what about excluding certain packages?

One thing this tool doesn't do a great job of is respecting consolidation by Target Framework (which is fine).  But in the instance of having a dynamic package version for different target frameworks, we'd like to exclude certain packages that we know aren't consolidated and are fine with that.

**Comment by olsh** [comment]
Hi @cmeyertons 
Thanks for the suggestion.
The feature is not implemented yet, I'll probably implement it when I have spare time. PR is welcome 😉

**Comment by olsh** [comment]
Added a new parameter `-e` for excluding packages in the 2.1.0 version
https://www.nuget.org/packages/dotnet-consolidate/2.1.0
