### ISSUE TITLE
Add version exclude pattern

### ISSUE THREAD

**Issue by Piedone** [olsh/dotnet-consolidate#47]
In our use case, we only want to exclude those packages of us from consolidation, that are alpha versions.

For example, we have the [Helpful Libraries](https://www.nuget.org/packages/Lombiq.HelpfulLibraries/) package what is a utility package widely used in our other projects. We might add some new features to it just for OtherProject. Then, we release Helpful Libraries as an alpha (like v8.0.3-alpha.0.lmbq-249) and reference that in OtherProject, of which we release an alpha too. However, since Helpful Libraries is used in dozens of other projects, we are forced to update the reference there too.

This is useful if we release a new non-alpha version of Helpful Libraries, since then we indeed want to bring up all of our projects to the same level. However, this is unnecessary for alpha versions.

Do you think this would be a useful feature, @olsh? If yes, I'd give implementing it a shot, following the pattern of https://github.com/olsh/dotnet-consolidate/pull/25.

**Comment by Piedone** [comment]
@olsh could you please comment? I'd be able to contribute the feature if you agree.

**Comment by olsh** [comment]
@Piedone yes, sure, that is a good feature to have.

**Comment by Piedone** [comment]
Thank you! I'm more or less done: https://github.com/olsh/dotnet-consolidate/pull/50

**Comment by Piedone** [comment]
The title of https://github.com/olsh/dotnet-consolidate/releases/tag/4.1.0 should be 4.1.0 I think.

**Comment by olsh** [comment]
Yes, thank you! 👍🏻
