### ISSUE TITLE
Solution parameter is required :(

### ISSUE THREAD

**Issue by mmo-mikhail** [olsh/dotnet-consolidate#8]
ER: Would be great to be able to run the utility without having to pass solution parameter, it such case I expect it looking up all solutions in a current folder and then process it as usual array of solutions.

**Comment by ITDancer13** [comment]
@olsh Do you want this to be implemented?
If yes, let me know and I'll create a PR for that.

**Comment by olsh** [comment]
Hi @ITDancer13 
Yes, PR is welcome.

**Comment by ITDancer13** [comment]
@olsh okay, will do :)
There is already one from me which upgrades to .NET 6 and I'd like to build on top of that. Review required :)
